#!/bin/bash
# https://www.reddit.com/r/bashonubuntuonwindows/comments/adrpc0/comment/edkkwty/?utm_source=share&utm_medium=web2x&context=3
name="$0"
[[ "$name" == */* ]] || name="./$name"
name="${name##*/}"

if [ "$name" == "wsl-shim" ] ; then
    if [ -n "$1" ]; then
        echo "link $1 to wsl-shim"
        ln -s "$0" "$1"
        exit 0
    else
        echo "usage: $0 <link-name>"
        exit 1
    fi
fi

(which $name.exe > /dev/null && $name.exe "$@") \
    || (which $name.ps1 > /dev/null && powershell.exe $name.ps1 "$@") \
    || (which $name.cmd > /dev/null && cmd.exe /c $name.cmd "$@") \
    || (which $name.bat > /dev/null && cmd.exe /c $name.bat "$@")
