#!/bin/bash
# https://www.reddit.com/r/bashonubuntuonwindows/comments/adrpc0/comment/edkkwty/?utm_source=share&utm_medium=web2x&context=3
name="$0"
[[ "$name" == */* ]] || name="./$name"
name="${name##*/}"

if [ "$name" == "wslshim" ] ; then
    ln -s wslshim $1
    exit 0
fi

(which $name.exe > /dev/null && $name.exe "$@") \
    || (which $name.ps1 > /dev/null && powershell.exe $name.ps1 "$@") \
    || (which $name.cmd > /dev/null && cmd.exe /c $name.cmd "$@") \
    || (which $name.bat > /dev/null && cmd.exe /c $name.bat "$@")
